language: node_js java
node_js:
  - 0.10
jdk:
  - oraclejdk7
before_script:
  - cd $TRAVIS_BUILD_DIR/ginkgo-seed/spa
  - npm install -g bower grunt-cli
  - npm install
  - bower install
  - grunt build
script:
  - mvn clean install -f $TRAVIS_BUILD_DIR/ginkgo-seed/pom.xml
  - grunt test
