language: node_js java
node_js:
  - 0.10
jdk:
  - oraclejdk7
before_script:
  - npm install -g bower grunt-cli
  - npm install
  - bower install
  - grunt --base ginkgo-seed/spa --gruntfile --base ginkgo-seed/spa/Gruntfile.js build
script:
  - mvn clean install -f ginkgo-seed/pom.xml
  - grunt --base ginkgo-seed/spa --gruntfile --base ginkgo-seed/spa/Gruntfile.js test
