language: node_js java
node_js:
  - '0.10'
jdk:
  - oraclejdk7
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
before_script: 
  - grunt build --base ginkgo-seed/spa
script:
  - mvn clean install -f ginkgo-seed/pom.xml
  - grunt test --base ginkgo-seed/spa
